#!/bin/bash
#PBS -N batchforc
#PBS -A P48500028
#PBS -q main
#PBS -l walltime=08:00:00
#PBS -l select=1:ncpus=36:mpiprocs=36
#==========================================================================


# Instead of setting individually, source a config file generated by the subsetting tool:
source batch_forcing_subset_config_new.txt

#==========================================================================
if [ ! -e $out_path ]; then
    mkdir -p $out_path
fi

echo "site_no : $site_no"
echo "west_east : $west_east"
echo "south_north : $south_north"
echo "out_path : $out_path"
echo "in_path : $in_path"
#==========================================================================
# Start the program...
module load nco
module load mpt

for year in `seq $year_start $year_end`; do
echo "year: $year"

if [ ! -z $PBS_JOBID ]; then
    echo wtf
    export PBS=true
    export MPI_SHEPHERD=true
    export RUNCMD="mpiexec_mpt launch_cf.sh"
    export JOBNAME=$PBS_JOBNAME
    chunk_size=`cat $PBS_NODEFILE | wc -l`
else
    chunk_size=36 # cheyenne default.
fi
echo "chunk_size: $chunk_size"

file_list=`ls -1 ${in_path}/$year*`
n_files=$(echo "$file_list" | wc -l)

n_chunks=$(echo "scale=0; $n_files / $chunk_size" | bc)
n_remain=$(echo "scale=0; $n_files % $chunk_size" | bc)

echo "n_files: $n_files"
echo "n_chunks: $n_chunks"
echo "n_remain: $n_remain"

cc=0 # incase this for loop is skipped
for cc in `seq 1 $n_chunks`; do
    
    #cmd_file_name=cmd_file_chunk_${cc}.txt
    cmd_file_name=cmd_file_chunk_${site_no}_${year}.txt
    rm -f $cmd_file_name
    chunk_end=$(echo "scale=0; $chunk_size * $cc" | bc)
    #echo
    #echo "chunk_end: $chunk_end"
    chunk_files=$(echo "$file_list" | head -n $chunk_end | tail -n $chunk_size)
    #echo "$chunk_files"
    for ff in `seq 1 $chunk_size`; do
        ff=$(echo "$chunk_files" | head -n $ff | tail -n 1)
        file_base=$(basename $ff)
        cmd="ncks -O -d ${west_east} -d ${south_north} ${ff} ${out_path}/${file_base}" 
        echo "$cmd" >> $cmd_file_name
    done

    mpiexec_mpt launch_cf.sh ./${cmd_file_name} >& ${cmd_file_name}.stdouterr

done

# The remainder chunk for the year
if [ $n_remain -eq 0 ]; then
    continue
fi

cc=$(echo "scale=0; $cc + 1" | bc)
#cmd_file_name=cmd_file_chunk_${cc}.txt
cmd_file_name=cmd_file_chunk_${site_no}_${year}.txt
rm -f $cmd_file_name
chunk_end=$(echo "scale=0; $chunk_size * $cc" | bc)
#echo
#echo "chunk_end: $chunk_end"
chunk_files=$(echo "$file_list" | head -n $chunk_end | tail -n $n_remain)
for ff in `seq 1 $n_remain`; do
    ff=$(echo "$chunk_files" | head -n $ff | tail -n 1)
    file_base=$(basename $ff)
    cmd="ncks -O -d ${west_east} -d ${south_north} ${ff} ${out_path}/${file_base}" 
    echo "$cmd" >> $cmd_file_name
done

n_pad=$(echo "scale=0; $chunk_size - $n_remain" | bc)
pad_cmd="echo Just padding command."
for pp in `seq 1 $n_pad`; do
    echo "$pad_cmd" >> $cmd_file_name
done

mpiexec_mpt launch_cf.sh ./${cmd_file_name} >& ${cmd_file_name}.stdouterr

done

exit 0
